# Generated by Django 5.2.7 on 2025-10-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_booksavailable_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('book_file', models.FileField(upload_to='books/files/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Available Book',
                'verbose_name_plural': 'Available Books',
            },
        ),
        migrations.CreateModel(
            name='RequesterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_name', models.CharField(help_text='The name the user uses in the WhatsApp group.', max_length=150, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Full phone number (including country code, e.g., +255712345678).', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group Requester',
                'verbose_name_plural': 'Group Requesters',
            },
        ),
        migrations.DeleteModel(
            name='BooksAvailable',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ['request_date'], 'verbose_name': 'Book Request/Order', 'verbose_name_plural': 'Book Requests/Orders'},
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='book_author',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='fulfilled',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='user_name',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Notes on fulfillment, e.g., 'Sent via WhatsApp on 2025-10-23'."),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='fulfillment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('FULFILLED', 'Fulfilled (Sent to User)'), ('REJECTED', 'Rejected (e.g., Book Not Found)'), ('CONTACT', 'Contact Required (Issue with Request)')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='book_requested',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books_app.bookavailable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books_app.requesterprofile'),
            preserve_default=False,
        ),
    ]
