# Generated by Django 5.2.7 on 2025-10-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_bookavailable_requesterprofile_delete_booksavailable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='book_author',
            field=models.CharField(blank=True, help_text='Author of the requested book.', max_length=100),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='book_title',
            field=models.CharField(default=1, help_text='Title of the requested book.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='book_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books_app.bookavailable'),
        ),
    ]
