# Generated by Django 5.2.7 on 2025-10-23 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0004_bookrequest_book_author_bookrequest_book_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requesterprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile picture.', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='requesterprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requesterprofile',
            name='whatsapp_number',
            field=models.CharField(default=1, help_text='Required. Full phone number including country code, e.g., +255712345678.', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
