# Generated by Django 4.2.23 on 2025-10-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0005_requesterprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesterprofile',
            name='whatsapp_name',
            field=models.CharField(help_text='The name the user uses in the WhatsApp group.', max_length=150),
        ),
    ]
