# Generated by Django 4.2.23 on 2025-10-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0006_alter_requesterprofile_whatsapp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesterprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Optional. Full phone number including country code, e.g., +255712345678.', max_length=20, null=True, unique=True),
        ),
    ]
