# Generated by Django 4.2.23 on 2025-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0007_alter_requesterprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Notes on fulfillment, 'Sent via WhatsApp on 2025-10-23'."),
        ),
    ]
