# Generated by Django 5.2.8 on 2025-11-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0008_alter_bookrequest_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookavailable',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the book has been downloaded.'),
        ),
        migrations.AddField(
            model_name='bookavailable',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the book detail page has been viewed.'),
        ),
    ]
